baseURL = "http://localhost:1313"
languageCode = 'en-us'
title = 'kochbuch'


pagination.pagerSize = 9 
pagination.path = "page"


# [[module.mounts]]
#   source = "assets"
#   target = "assets"
# [[module.mounts]]
#   source = "src"
#   target = "assets"
# [[module.mounts]]
#   source = "content"
#   target = "content"
# [[module.mounts]]
#   source = "static"
#   target = "static"
# [[module.mounts]]
#   source = "layouts"
#   target = "layouts"
#
# [markup.goldmark.renderer]
#   unsafe = true # Allow HTML in md files
#
#   [markup.highlight]
#     codeFences = true
#     guessSyntax = false
#     hl_Lines = ""
#     lineNoStart = 1
#     lineNos = false
#     lineNumbersInTable = true
#     noClasses = false
#     tabWidth = 4
